### ISSUE TITLE
Stats improvements

### ISSUE THREAD

**Issue by kuegi** [Krysh90/vault-maxi-web#16]
- [x] add loan-circle:
split up into
* DUSD loans from manual vaults
* dToken loans from manual vaults
* dusd loans from bot vaults
* dToken loans from bot vaults

- [x] rename "total" in collateral section to "total from bots" and add real "total" for total collateral from all nonEmpty vaults (included in new data)

- [x] change color of "manual Vaults" to prevent confusion with double-mint strategy (both are dark gray now)
- [x] add usedVaults-collRatio to avgCollRatio history

**Comment by Krysh90** [comment]
add info box with a small description, last updated and used parameters

**Comment by Krysh90** [comment]
remove custom y axis on history number of vaults
